### ISSUE TITLE
Infinite Spin Atk

### ISSUE THREAD

**Issue by trithai1** [KhangDangPham/Team-Vania-Platformer#1]
Spin attack doesn't stop after certain inputs

**Comment by KhangDangPham** [comment]
Please make a new branch named Quangtri-Issue1 in the repository and then redo the pull request so that we can solve the merge conflict.

**Comment by trithai1** [comment]
Actually, I'll close this issue and add the changes with the "Enhance scripts" Issue when I complete it

**Comment by KhangDangPham** [comment]
Okay
